---
# Prepare host for the FreeIPA installation
- hosts: ipa
  tasks:
  - name: Prepare the basement for ipa installation
    include_role:
      name: ipa_base

# Configure the master
- hosts: ipamaster
  tasks:
  - name: Configure the master server
    include_role:
      name: ipa_master

# Configure replicas
- hosts: ipareplicas
  serial: 1
  tasks:
  - name: Configure replica servers
    include_role:
      name: ipa_replica
# Disable DNS recursive requests to disable DNS ddos amplification
- hosts: ipa
  serial: 1
  tasks:
  - name: Change Bind config and restart FreeIPA
    include: norecursive.yml
...
