---
# tasks file for ipa_master
- name: Copy the file with options for master installation
  import_tasks: config.yml
- name: Install FreeIPA master server
  import_tasks: install.yml
- name: Lunch FreeIPA master server
  import_tasks: run.yml
...
