---
- name: Pull FreeIPA container image
  podman_image:
    name: docker.io/freeipa/freeipa-server
    state: present
- name: Create a network namespace for FreeIPA container
  command: /usr/local/sbin/ipa_net.py
...
