- name: install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
  - epel-release
  - python3-pyroute2
  - podman
- name: Set container_manage_cgroup selinux bolean
  seboolean:
    name: container_manage_cgroup
    state: yes
    persistent: yes
